### PR TITLE
switched failing test suites from detailed-0.9 to exitcode-stdio-1.0

### PR DESCRIPTION
**Pull request by michaxm**
... which is to my knowledge still defunct (_please_ correct me, if I am wrong)

### CODE REVIEW

**Comment by michaxm** [comment]
See
https://github.com/jberthold/packman/issues/4
or rather the gist linked there:
https://gist.github.com/rrnewton/5f8b1db0a3f264ab48b7

**Comment by jberthold** [comment]
Thanks for your PR. Unfortunately, the situation is a bit more complicated:
The three detailed-0.9 tests (`alltests`, `testmthread`, `quickchecktest`) work fine with ghc-7.10, which brings in Cabal-1.22.*. However, they do not compile with ghc-7.8, which comes with Cabal-1.18.
If I put a constraint `Cabal >= 1.20` (where the LibV09 module exists), the tests cannot be built with ghc-7.8 either, because the library depends on ghc-7.8, which fixes the Cabal version to 1.18. 

I would be more inclined to put your PR on a ghc-7.8 branch than to use it for the main line.
Would that be enough to work with the library?

I have created a branch `wip/fixtests` where I will try to split the versions that lead to this conflict. Hope to have more time for this, and other things related to `packman` early next week.

**Comment by jberthold** [comment]
@michaxm Could you please test the code from #8 with your setup?
(switches to Cabal>1.20, works for me with two different ghc-7.8 installations (one clean, one rather custom)
I can adapt your PR to use `exitcode` with ghc-7.8 and `detailed` otherwise, but prefer the other variant if it works for you.

**Comment by michaxm** [comment]
Hi,

good news, using cabal-install (and sandboxes) this works for me.

Executing the tests with stack won't work out of the box, because the
standard resolution plans are not to be able to find a solution on
these constraints - but if cabal can do it, stack should be
configurable, too, I might try that on next occasion. And the error
message is now a lot more meaningful.

Please use your changes and discard mine, finally a working example
with detailed-0.9 :) .

Cheers,
Axel

2015-11-24 12:10 GMT+01:00, Jost Berthold notifications-at-github.com
|github/relay mannhardt@gmail| <xbcagqeeqt@sneakemail.com>:

**Pull request closed without merging**
